apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: test-hello-world-appset
  namespace: argocd
spec:
  # See docs for available generators and their specs.
  generators:
    - merge:
        # The following line is commented, representing the default behaviour
        # allowDuplicates: true
        mergeKeys:
          - env
        generators:
          - list:
              elements:
                - env: staging
                  server: https1234
                - env: staging
                  server: https:1357
                - env: production
                  server: https2468
          - list:
              elements:
                - env: staging
                  redis: 'false'
                - env: production
                  redis: 'true'
  # Determines whether go templating will be used in the `template` field below.
  goTemplate: false
  # Optional list of go templating options, see https://pkg.go.dev/text/template#Template.Option
  # This is only relevant if `goTemplate` is true
  goTemplateOptions: ["missingkey="]
  # These fields are identical to the Application spec.
  template:
    metadata:
      name: '{{env}}-{{server}}'
      labels:
        size: '{{env}}'
        color: '{{redis}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/argoproj/argocd-example-apps
        targetRevision: HEAD
        path: guestbook
      destination:
        server: https://kubernetes.default.svc
        namespace: guestbook
  # This sync policy pertains to the ApplicationSet, not to the Applications it creates.
  syncPolicy:
    # Determines whether the controller will delete Applications when an ApplicationSet is deleted.
    preserveResourcesOnDeletion: false
  # Alpha feature to determine the order in which ApplicationSet applies changes.

